[[ISSUERS]]
address = "r39yS2i4hGDA9mn1NNo98mETPb4W8aQ8Zv"
name = "AlphaJetBridge"

[[TOKENS]]
issuer = "r39yS2i4hGDA9mn1NNo98mETPb4W8aQ8Zv"
currency = "AJB"
name = "AlphaJetBridge"
desc = "A cryptocurrency for gaming and microtransactions, powered by XRP Ledger."
icon = "https://raw.githubusercontent.com/AlphaJetBridge/AJB/refs/heads/main/ajb.png"

[[TOKENS.WEBLINKS]]
url = "https://ajb-token.netlify.app/"
type = "website"
title = "Official Website"


[[TOKENS.WEBLINKS]]
url = "https://x.com/AlphaJetBridge"
type = "socialmedia"
